### ISSUE TITLE
python dependencies

### ISSUE THREAD

**Issue by gegnew** [bassio/omicexperiment#1]
Hi, 

I may be missing something critical, but I can't get this to work due to biom-format. That package requires Python 2, and won't install at all in a virtualenv with Python 3 (breaks gcc). If I install in a Python 2 venv, then run one of your test Jupyter notebooks on a Python 2 kernel, it breaks on syntax. If I run it on a Python 3 kernel, import can't find "biom". Any thoughts?

Thanks,

-g

**Comment by gegnew** [comment]
Nevermind, it works find if you use Python 3.5 instead of 3.7

**Comment by bassio** [comment]
Hi gegnew,
That is interesting.
I wonder what makes it not work with python 3.7.
I will test it out on a new virtualenv.
Thank you for reporting this! Please let me know if you have any suggestions for this package!
